[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lens_payment = "4JwBm4nCWHmxRrtc2bSeM6idcsgoBkNdq8VNyFdYYVbR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
